/**
 * Mock数据服务
 * 用于前端功能验收，不依赖后端数据库
 */

import type { MetadataTable, MetadataField } from '../types/metadata';
import type { ApprovalFlow, OperationHistory } from '../types/approval';
import { DataSourceType, WarehouseLayer, SensitivityLevel, ImportanceLevel, ApprovalStatus, OperationType } from '../types/enums';

// ==================== 元数据表Mock数据 ====================

export const mockTables: MetadataTable[] = [
  {
    id: 1,
    tableName: 'user_info',
    databaseName: 'edw_user_db',
    dataSource: DataSourceType.HIVE,
    tableComment: '用户基础信息表，存储用户的基本属性信息，包括注册信息、个人资料等',
    hiveAccount: 'hotel',
    tableSize: 10737418240, // 10GB
    warehouseLayer: WarehouseLayer.EDW,
    themeFirst: 'usr',
    themeSecond: 'con',
    sensitivityLevel: SensitivityLevel.L2,
    importanceLevel: ImportanceLevel.P0,
    partitionType: '增量分区',
    partitionRetentionDays: 730,
    updateFrequency: '每日',
    owner: 'zhangsan',
    customTags: '核心表,用户,实时',
    createSql: 'CREATE TABLE edw_user_db.user_info (...)',
    createBy: 'zhangsan',
    createTime: '2024-01-10 10:30:00',
    updateBy: 'zhangsan',
    updateTime: '2024-01-15 15:20:00',
  },
  {
    id: 2,
    tableName: 'order_detail',
    databaseName: 'dwd_order_db',
    dataSource: DataSourceType.HIVE,
    tableComment: '订单明细表，记录所有订单的详细信息，包括订单商品、金额、状态等',
    hiveAccount: 'hotel',
    tableSize: 53687091200, // 50GB
    warehouseLayer: WarehouseLayer.DWD,
    themeFirst: 'ord',
    themeSecond: 'dtl',
    sensitivityLevel: SensitivityLevel.L3,
    importanceLevel: ImportanceLevel.P0,
    partitionType: '全量分区',
    partitionRetentionDays: 365,
    updateFrequency: '每小时',
    owner: 'lisi',
    customTags: '核心表,订单,高频',
    createSql: 'CREATE TABLE dwd_order_db.order_detail (...)',
    createBy: 'lisi',
    createTime: '2024-02-05 09:00:00',
    updateBy: 'lisi',
    updateTime: '2024-03-10 14:30:00',
  },
  {
    id: 3,
    tableName: 'hotel_booking',
    databaseName: 'cdm_hotel_db',
    dataSource: DataSourceType.BIGQUERY,
    tableComment: '酒店预订汇总表，统计酒店预订的关键指标，支持BI报表查询',
    hiveAccount: 'hotel',
    tableSize: 2147483648, // 2GB
    warehouseLayer: WarehouseLayer.CDM,
    themeFirst: 'prd',
    themeSecond: 'htl',
    sensitivityLevel: SensitivityLevel.L1,
    importanceLevel: ImportanceLevel.P1,
    partitionType: '增量分区',
    partitionRetentionDays: 180,
    updateFrequency: '每日',
    owner: 'wangwu',
    customTags: '酒店,汇总表',
    createSql: 'CREATE TABLE cdm_hotel_db.hotel_booking (...)',
    createBy: 'wangwu',
    createTime: '2024-03-01 11:20:00',
    updateBy: 'wangwu',
    updateTime: '2024-03-15 16:45:00',
  },
  {
    id: 4,
    tableName: 'user_behavior_log',
    databaseName: 'ods_log_db',
    dataSource: DataSourceType.CLICKHOUSE,
    tableComment: '用户行为日志表，记录用户在APP和网站上的所有操作行为',
    hiveAccount: 'bieng',
    tableSize: 107374182400, // 100GB
    warehouseLayer: WarehouseLayer.ODS,
    themeFirst: 'ubt',
    themeSecond: 'log',
    sensitivityLevel: SensitivityLevel.L2,
    importanceLevel: ImportanceLevel.P1,
    partitionType: '增量分区',
    partitionRetentionDays: 90,
    updateFrequency: '实时',
    owner: 'zhaoliu',
    customTags: '日志,用户行为,大数据',
    createSql: 'CREATE TABLE ods_log_db.user_behavior_log (...)',
    createBy: 'zhaoliu',
    createTime: '2024-01-20 08:30:00',
    updateBy: 'zhaoliu',
    updateTime: '2024-03-18 10:15:00',
  },
  {
    id: 5,
    tableName: 'payment_transaction',
    databaseName: 'dwd_finance_db',
    dataSource: DataSourceType.HIVE,
    tableComment: '支付交易明细表，存储所有支付交易的详细记录，包括支付渠道、金额、状态等',
    hiveAccount: 'hotel',
    tableSize: 21474836480, // 20GB
    warehouseLayer: WarehouseLayer.DWD,
    themeFirst: 'fin',
    themeSecond: 'pay',
    sensitivityLevel: SensitivityLevel.L4,
    importanceLevel: ImportanceLevel.P0,
    partitionType: '增量分区',
    partitionRetentionDays: 1095,
    updateFrequency: '每小时',
    owner: 'sunqi',
    customTags: '核心表,支付,金融',
    createSql: 'CREATE TABLE dwd_finance_db.payment_transaction (...)',
    createBy: 'sunqi',
    createTime: '2024-02-15 14:00:00',
    updateBy: 'sunqi',
    updateTime: '2024-03-20 09:30:00',
  },
  {
    id: 6,
    tableName: 'product_inventory',
    databaseName: 'mid_product_db',
    dataSource: DataSourceType.PAIMON,
    tableComment: '商品库存中间表，实时更新商品库存状态',
    hiveAccount: 'hotel_tech',
    tableSize: 1073741824, // 1GB
    warehouseLayer: WarehouseLayer.MID,
    themeFirst: 'prd',
    themeSecond: 'inv',
    sensitivityLevel: SensitivityLevel.L1,
    importanceLevel: ImportanceLevel.P2,
    partitionType: '全量分区',
    partitionRetentionDays: 30,
    updateFrequency: '每15分钟',
    owner: 'zhouba',
    customTags: '库存,实时',
    createSql: 'CREATE TABLE mid_product_db.product_inventory (...)',
    createBy: 'zhouba',
    createTime: '2024-03-05 10:00:00',
    updateBy: 'zhouba',
    updateTime: '2024-03-19 11:20:00',
  },
  {
    id: 7,
    tableName: 'customer_profile',
    databaseName: 'cdm_user_db',
    dataSource: DataSourceType.HIVE,
    tableComment: '客户画像表，整合用户的多维度特征，支持精准营销',
    hiveAccount: 'hotel',
    tableSize: 5368709120, // 5GB
    warehouseLayer: WarehouseLayer.CDM,
    themeFirst: 'usr',
    themeSecond: 'mem',
    sensitivityLevel: SensitivityLevel.L3,
    importanceLevel: ImportanceLevel.P1,
    partitionType: '全量分区',
    partitionRetentionDays: 365,
    updateFrequency: '每日',
    owner: 'wujiu',
    customTags: '画像,用户,营销',
    createSql: 'CREATE TABLE cdm_user_db.customer_profile (...)',
    createBy: 'wujiu',
    createTime: '2024-02-20 13:30:00',
    updateBy: 'wujiu',
    updateTime: '2024-03-21 15:00:00',
  },
  {
    id: 8,
    tableName: 'marketing_campaign',
    databaseName: 'dwd_marketing_db',
    dataSource: DataSourceType.ICEBERG,
    tableComment: '营销活动详情表，记录所有营销活动的配置和执行情况',
    hiveAccount: 'bieng',
    tableSize: 3221225472, // 3GB
    warehouseLayer: WarehouseLayer.DWD,
    themeFirst: 'mkt',
    themeSecond: 'cmp',
    sensitivityLevel: SensitivityLevel.L1,
    importanceLevel: ImportanceLevel.P2,
    partitionType: '增量分区',
    partitionRetentionDays: 365,
    updateFrequency: '每日',
    owner: 'zhengshi',
    customTags: '营销,活动',
    createSql: 'CREATE TABLE dwd_marketing_db.marketing_campaign (...)',
    createBy: 'zhengshi',
    createTime: '2024-03-08 09:45:00',
    updateBy: 'zhengshi',
    updateTime: '2024-03-22 14:20:00',
  },
  {
    id: 9,
    tableName: 'flight_booking',
    databaseName: 'dwd_flight_db',
    dataSource: DataSourceType.STARROCKS,
    tableComment: '机票预订明细表，存储机票预订的完整信息',
    hiveAccount: 'flight',
    tableSize: 15032385536, // 14GB
    warehouseLayer: WarehouseLayer.DWD,
    themeFirst: 'ord',
    themeSecond: 'flt',
    sensitivityLevel: SensitivityLevel.L2,
    importanceLevel: ImportanceLevel.P1,
    partitionType: '增量分区',
    partitionRetentionDays: 545,
    updateFrequency: '每小时',
    owner: 'wushi',
    customTags: '机票,预订',
    createSql: 'CREATE TABLE dwd_flight_db.flight_booking (...)',
    createBy: 'wushi',
    createTime: '2024-02-28 11:00:00',
    updateBy: 'wushi',
    updateTime: '2024-03-23 10:30:00',
  },
  {
    id: 10,
    tableName: 'dim_region',
    databaseName: 'dim_common_db',
    dataSource: DataSourceType.HIVE,
    tableComment: '地区维度表，存储国家、省份、城市等地理信息',
    hiveAccount: 'hotel',
    tableSize: 104857600, // 100MB
    warehouseLayer: WarehouseLayer.DIM,
    themeFirst: 'dim',
    themeSecond: 'geo',
    sensitivityLevel: SensitivityLevel.L1,
    importanceLevel: ImportanceLevel.P3,
    partitionType: '全量分区',
    partitionRetentionDays: 0,
    updateFrequency: '每周',
    owner: 'zhengshi',
    customTags: '维度表,地区',
    createSql: 'CREATE TABLE dim_common_db.dim_region (...)',
    createBy: 'zhengshi',
    createTime: '2024-01-05 10:00:00',
    updateBy: 'zhengshi',
    updateTime: '2024-03-10 09:00:00',
  },
];

// ==================== 元数据字段Mock数据 ====================

export const mockFields: Record<number, MetadataField[]> = {
  1: [ // user_info表的字段
    {
      id: 1,
      tableId: 1,
      fieldName: 'user_id',
      fieldComment: '用户唯一标识，主键',
      fieldType: 'BIGINT',
      fieldOrder: 1,
      isPrimaryKey: 1,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: undefined,
      createBy: 'zhangsan',
      createTime: '2024-01-10 10:30:00',
      updateBy: 'zhangsan',
      updateTime: '2024-01-10 10:30:00',
    },
    {
      id: 2,
      tableId: 1,
      fieldName: 'user_name',
      fieldComment: '用户姓名',
      fieldType: 'STRING',
      fieldOrder: 2,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 1,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L3,
      defaultValue: undefined,
      createBy: 'zhangsan',
      createTime: '2024-01-10 10:30:00',
      updateBy: 'zhangsan',
      updateTime: '2024-01-10 10:30:00',
    },
    {
      id: 3,
      tableId: 1,
      fieldName: 'mobile',
      fieldComment: '手机号码',
      fieldType: 'STRING',
      fieldOrder: 3,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 1,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L4,
      defaultValue: undefined,
      createBy: 'zhangsan',
      createTime: '2024-01-10 10:30:00',
      updateBy: 'zhangsan',
      updateTime: '2024-01-10 10:30:00',
    },
    {
      id: 4,
      tableId: 1,
      fieldName: 'email',
      fieldComment: '邮箱地址',
      fieldType: 'STRING',
      fieldOrder: 4,
      isPrimaryKey: 0,
      isNullable: 1,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L2,
      defaultValue: undefined,
      createBy: 'zhangsan',
      createTime: '2024-01-10 10:30:00',
      updateBy: 'zhangsan',
      updateTime: '2024-01-10 10:30:00',
    },
    {
      id: 5,
      tableId: 1,
      fieldName: 'register_time',
      fieldComment: '注册时间',
      fieldType: 'TIMESTAMP',
      fieldOrder: 5,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: 'CURRENT_TIMESTAMP',
      createBy: 'zhangsan',
      createTime: '2024-01-10 10:30:00',
      updateBy: 'zhangsan',
      updateTime: '2024-01-10 10:30:00',
    },
    {
      id: 6,
      tableId: 1,
      fieldName: 'user_status',
      fieldComment: '用户状态：0-正常，1-冻结，2-注销',
      fieldType: 'TINYINT',
      fieldOrder: 6,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: '0',
      createBy: 'zhangsan',
      createTime: '2024-01-10 10:30:00',
      updateBy: 'zhangsan',
      updateTime: '2024-01-10 10:30:00',
    },
  ],
  2: [ // order_detail表的字段
    {
      id: 7,
      tableId: 2,
      fieldName: 'order_id',
      fieldComment: '订单ID，主键',
      fieldType: 'BIGINT',
      fieldOrder: 1,
      isPrimaryKey: 1,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: undefined,
      createBy: 'lisi',
      createTime: '2024-02-05 09:00:00',
      updateBy: 'lisi',
      updateTime: '2024-02-05 09:00:00',
    },
    {
      id: 8,
      tableId: 2,
      fieldName: 'user_id',
      fieldComment: '用户ID',
      fieldType: 'BIGINT',
      fieldOrder: 2,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L2,
      defaultValue: undefined,
      createBy: 'lisi',
      createTime: '2024-02-05 09:00:00',
      updateBy: 'lisi',
      updateTime: '2024-02-05 09:00:00',
    },
    {
      id: 9,
      tableId: 2,
      fieldName: 'product_id',
      fieldComment: '商品ID',
      fieldType: 'BIGINT',
      fieldOrder: 3,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: undefined,
      createBy: 'lisi',
      createTime: '2024-02-05 09:00:00',
      updateBy: 'lisi',
      updateTime: '2024-02-05 09:00:00',
    },
    {
      id: 10,
      tableId: 2,
      fieldName: 'order_amount',
      fieldComment: '订单金额（元）',
      fieldType: 'DECIMAL(10,2)',
      fieldOrder: 4,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L3,
      defaultValue: '0.00',
      createBy: 'lisi',
      createTime: '2024-02-05 09:00:00',
      updateBy: 'lisi',
      updateTime: '2024-02-05 09:00:00',
    },
    {
      id: 11,
      tableId: 2,
      fieldName: 'order_status',
      fieldComment: '订单状态：0-待支付，1-已支付，2-已取消，3-已完成',
      fieldType: 'TINYINT',
      fieldOrder: 5,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: '0',
      createBy: 'lisi',
      createTime: '2024-02-05 09:00:00',
      updateBy: 'lisi',
      updateTime: '2024-02-05 09:00:00',
    },
    {
      id: 12,
      tableId: 2,
      fieldName: 'create_time',
      fieldComment: '创建时间',
      fieldType: 'TIMESTAMP',
      fieldOrder: 6,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: 'CURRENT_TIMESTAMP',
      createBy: 'lisi',
      createTime: '2024-02-05 09:00:00',
      updateBy: 'lisi',
      updateTime: '2024-02-05 09:00:00',
    },
  ],
};

// 为其他表生成基础字段
for (let i = 3; i <= 10; i++) {
  mockFields[i] = [
    {
      id: i * 10 + 1,
      tableId: i,
      fieldName: 'id',
      fieldComment: '主键ID',
      fieldType: 'BIGINT',
      fieldOrder: 1,
      isPrimaryKey: 1,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: undefined,
      createBy: mockTables[i - 1].createBy,
      createTime: mockTables[i - 1].createTime,
      updateBy: mockTables[i - 1].updateBy,
      updateTime: mockTables[i - 1].updateTime,
    },
    {
      id: i * 10 + 2,
      tableId: i,
      fieldName: 'name',
      fieldComment: '名称',
      fieldType: 'STRING',
      fieldOrder: 2,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: undefined,
      createBy: mockTables[i - 1].createBy,
      createTime: mockTables[i - 1].createTime,
      updateBy: mockTables[i - 1].updateBy,
      updateTime: mockTables[i - 1].updateTime,
    },
    {
      id: i * 10 + 3,
      tableId: i,
      fieldName: 'create_time',
      fieldComment: '创建时间',
      fieldType: 'TIMESTAMP',
      fieldOrder: 3,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: 'CURRENT_TIMESTAMP',
      createBy: mockTables[i - 1].createBy,
      createTime: mockTables[i - 1].createTime,
      updateBy: mockTables[i - 1].updateBy,
      updateTime: mockTables[i - 1].updateTime,
    },
    {
      id: i * 10 + 4,
      tableId: i,
      fieldName: 'update_time',
      fieldComment: '更新时间',
      fieldType: 'TIMESTAMP',
      fieldOrder: 4,
      isPrimaryKey: 0,
      isNullable: 0,
      isEncrypted: 0,
      isPartitionKey: 0,
      sensitivityLevel: SensitivityLevel.L1,
      defaultValue: 'CURRENT_TIMESTAMP',
      createBy: mockTables[i - 1].createBy,
      createTime: mockTables[i - 1].createTime,
      updateBy: mockTables[i - 1].updateBy,
      updateTime: mockTables[i - 1].updateTime,
    },
  ];
}

// ==================== 审批流程Mock数据 ====================

export const mockApprovals: ApprovalFlow[] = [
  {
    id: 1,
    flowNo: 'APPR-2024-001',
    tableId: 1,
    approvalType: 'UPDATE',
    status: ApprovalStatus.PENDING,
    submitter: 'zhangsan',
    submitTime: '2024-03-22 10:30:00',
    approver: undefined,
    approveTime: undefined,
    approveComment: undefined,
    changeContent: JSON.stringify({
      tableName: 'user_info',
      changes: ['修改表描述', '新增字段user_level'],
    }),
    createBy: 'zhangsan',
    createTime: '2024-03-22 10:30:00',
    updateBy: 'zhangsan',
    updateTime: '2024-03-22 10:30:00',
  },
  {
    id: 2,
    flowNo: 'APPR-2024-002',
    tableId: 2,
    approvalType: 'UPDATE',
    status: ApprovalStatus.APPROVED,
    submitter: 'lisi',
    submitTime: '2024-03-20 14:20:00',
    approver: 'admin',
    approveTime: '2024-03-21 09:15:00',
    approveComment: '修改合理，同意通过',
    changeContent: JSON.stringify({
      tableName: 'order_detail',
      changes: ['优化表注释', '修改字段order_status的注释'],
    }),
    createBy: 'lisi',
    createTime: '2024-03-20 14:20:00',
    updateBy: 'admin',
    updateTime: '2024-03-21 09:15:00',
  },
  {
    id: 3,
    flowNo: 'APPR-2024-003',
    tableId: 5,
    approvalType: 'UPDATE',
    status: ApprovalStatus.PUBLISHED,
    submitter: 'sunqi',
    submitTime: '2024-03-18 11:00:00',
    approver: 'admin',
    approveTime: '2024-03-19 10:30:00',
    approveComment: '审批通过，已发布',
    changeContent: JSON.stringify({
      tableName: 'payment_transaction',
      changes: ['新增字段payment_channel', '修改敏感等级为L4'],
    }),
    createBy: 'sunqi',
    createTime: '2024-03-18 11:00:00',
    updateBy: 'admin',
    updateTime: '2024-03-19 15:00:00',
  },
  {
    id: 4,
    flowNo: 'APPR-2024-004',
    tableId: 3,
    approvalType: 'UPDATE',
    status: ApprovalStatus.REJECTED,
    submitter: 'wangwu',
    submitTime: '2024-03-21 16:00:00',
    approver: 'admin',
    approveTime: '2024-03-22 09:00:00',
    approveComment: '字段定义不清晰，需要重新整理后再提交',
    changeContent: JSON.stringify({
      tableName: 'hotel_booking',
      changes: ['新增字段booking_source'],
    }),
    createBy: 'wangwu',
    createTime: '2024-03-21 16:00:00',
    updateBy: 'admin',
    updateTime: '2024-03-22 09:00:00',
  },
  {
    id: 5,
    flowNo: 'APPR-2024-005',
    tableId: 7,
    approvalType: 'CREATE',
    status: ApprovalStatus.APPROVED,
    submitter: 'wujiu',
    submitTime: '2024-02-20 13:30:00',
    approver: 'admin',
    approveTime: '2024-02-21 10:00:00',
    approveComment: '新表创建合理，同意',
    changeContent: JSON.stringify({
      tableName: 'customer_profile',
      changes: ['创建客户画像表'],
    }),
    createBy: 'wujiu',
    createTime: '2024-02-20 13:30:00',
    updateBy: 'admin',
    updateTime: '2024-02-21 10:00:00',
  },
  {
    id: 6,
    flowNo: 'APPR-2024-006',
    tableId: 4,
    approvalType: 'UPDATE',
    status: ApprovalStatus.CANCELLED,
    submitter: 'zhaoliu',
    submitTime: '2024-03-19 15:00:00',
    approver: undefined,
    approveTime: undefined,
    approveComment: undefined,
    changeContent: JSON.stringify({
      tableName: 'user_behavior_log',
      changes: ['修改分区保留天数'],
    }),
    createBy: 'zhaoliu',
    createTime: '2024-03-19 15:00:00',
    updateBy: 'zhaoliu',
    updateTime: '2024-03-19 16:30:00',
  },
];

// ==================== 操作历史Mock数据 ====================

export const mockHistory: OperationHistory[] = [
  {
    id: 1,
    tableId: 1,
    tableName: 'user_info',
    databaseName: 'edw_user_db',
    operationType: OperationType.CREATE,
    operator: 'zhangsan',
    operationTime: '2024-01-10 10:30:00',
    beforeContent: undefined,
    afterContent: JSON.stringify({
      tableName: 'user_info',
      databaseName: 'edw_user_db',
      tableComment: '用户基础信息表',
    }),
    operationDesc: '创建用户基础信息表',
    createBy: 'system',
    createTime: '2024-01-10 10:30:00',
  },
  {
    id: 2,
    tableId: 1,
    tableName: 'user_info',
    databaseName: 'edw_user_db',
    operationType: OperationType.UPDATE,
    operator: 'zhangsan',
    operationTime: '2024-01-15 15:20:00',
    beforeContent: JSON.stringify({
      tableComment: '用户基础信息表',
    }),
    afterContent: JSON.stringify({
      tableComment: '用户基础信息表，存储用户的基本属性信息，包括注册信息、个人资料等',
    }),
    operationDesc: '优化表描述信息',
    createBy: 'system',
    createTime: '2024-01-15 15:20:00',
  },
  {
    id: 3,
    tableId: 2,
    tableName: 'order_detail',
    databaseName: 'dwd_order_db',
    operationType: OperationType.CREATE,
    operator: 'lisi',
    operationTime: '2024-02-05 09:00:00',
    beforeContent: undefined,
    afterContent: JSON.stringify({
      tableName: 'order_detail',
      databaseName: 'dwd_order_db',
      tableComment: '订单明细表',
    }),
    operationDesc: '创建订单明细表',
    createBy: 'system',
    createTime: '2024-02-05 09:00:00',
  },
  {
    id: 4,
    tableId: 2,
    tableName: 'order_detail',
    databaseName: 'dwd_order_db',
    operationType: OperationType.UPDATE,
    operator: 'lisi',
    operationTime: '2024-03-10 14:30:00',
    beforeContent: JSON.stringify({
      partitionRetentionDays: 180,
    }),
    afterContent: JSON.stringify({
      partitionRetentionDays: 365,
    }),
    operationDesc: '调整分区保留天数',
    createBy: 'system',
    createTime: '2024-03-10 14:30:00',
  },
  {
    id: 5,
    tableId: 5,
    tableName: 'payment_transaction',
    databaseName: 'dwd_finance_db',
    operationType: OperationType.UPDATE,
    operator: 'sunqi',
    operationTime: '2024-03-19 15:00:00',
    beforeContent: JSON.stringify({
      sensitivityLevel: 'L3',
      fields: ['payment_id', 'user_id', 'amount'],
    }),
    afterContent: JSON.stringify({
      sensitivityLevel: 'L4',
      fields: ['payment_id', 'user_id', 'amount', 'payment_channel'],
    }),
    operationDesc: '提升敏感等级，新增支付渠道字段',
    createBy: 'system',
    createTime: '2024-03-19 15:00:00',
  },
  {
    id: 6,
    tableId: 7,
    tableName: 'customer_profile',
    databaseName: 'cdm_user_db',
    operationType: OperationType.CREATE,
    operator: 'wujiu',
    operationTime: '2024-02-20 13:30:00',
    beforeContent: undefined,
    afterContent: JSON.stringify({
      tableName: 'customer_profile',
      databaseName: 'cdm_user_db',
      tableComment: '客户画像表',
    }),
    operationDesc: '创建客户画像表',
    createBy: 'system',
    createTime: '2024-02-20 13:30:00',
  },
  {
    id: 7,
    tableId: 3,
    tableName: 'hotel_booking',
    databaseName: 'cdm_hotel_db',
    operationType: OperationType.UPDATE,
    operator: 'wangwu',
    operationTime: '2024-03-15 16:45:00',
    beforeContent: JSON.stringify({
      updateFrequency: '每周',
    }),
    afterContent: JSON.stringify({
      updateFrequency: '每日',
    }),
    operationDesc: '调整更新频率',
    createBy: 'system',
    createTime: '2024-03-15 16:45:00',
  },
  {
    id: 8,
    tableId: 4,
    tableName: 'user_behavior_log',
    databaseName: 'ods_log_db',
    operationType: OperationType.CREATE,
    operator: 'zhaoliu',
    operationTime: '2024-01-20 08:30:00',
    beforeContent: undefined,
    afterContent: JSON.stringify({
      tableName: 'user_behavior_log',
      databaseName: 'ods_log_db',
      tableComment: '用户行为日志表',
    }),
    operationDesc: '创建用户行为日志表',
    createBy: 'system',
    createTime: '2024-01-20 08:30:00',
  },
  {
    id: 9,
    tableId: 8,
    tableName: 'marketing_campaign',
    databaseName: 'dwd_marketing_db',
    operationType: OperationType.CREATE,
    operator: 'zhengshi',
    operationTime: '2024-03-08 09:45:00',
    beforeContent: undefined,
    afterContent: JSON.stringify({
      tableName: 'marketing_campaign',
      databaseName: 'dwd_marketing_db',
      tableComment: '营销活动详情表',
    }),
    operationDesc: '创建营销活动详情表',
    createBy: 'system',
    createTime: '2024-03-08 09:45:00',
  },
  {
    id: 10,
    tableId: 9,
    tableName: 'flight_booking',
    databaseName: 'dwd_flight_db',
    operationType: OperationType.CREATE,
    operator: 'wushi',
    operationTime: '2024-02-28 11:00:00',
    beforeContent: undefined,
    afterContent: JSON.stringify({
      tableName: 'flight_booking',
      databaseName: 'dwd_flight_db',
      tableComment: '机票预订明细表',
    }),
    operationDesc: '创建机票预订明细表',
    createBy: 'system',
    createTime: '2024-02-28 11:00:00',
  },
];

// ==================== 模拟数据生成器ID ====================

let tableIdCounter = 11;
let fieldIdCounter = 1000;
let approvalIdCounter = 7;
let historyIdCounter = 11;

export const generateTableId = () => tableIdCounter++;
export const generateFieldId = () => fieldIdCounter++;
export const generateApprovalId = () => approvalIdCounter++;
export const generateHistoryId = () => historyIdCounter++;
